Fix Terraform configurations - add data source and provider

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -52,13 +52,13 @@ jobs:
             exit 1
           fi
 
-      - - name: Terraform Apply or Destroy
+          - name: Terraform Apply or Destroy
           run: |
-          if [ "${{ github.event.inputs.action }}" == "apply" ]; then
-          terraform apply -auto-approve tfplan
-          elif [ "${{ github.event.inputs.action }}" == "destroy" ]; then
-          terraform destroy -auto-approve
-          else
-          echo "Invalid action: ${{ github.event.inputs.action }}"
-          exit 1
-          fi
+            if [ "${{ github.event.inputs.action }}" == "apply" ]; then
+            terraform apply -auto-approve tfplan
+            elif [ "${{ github.event.inputs.action }}" == "destroy" ]; then
+            terraform destroy -auto-approve
+            else
+            echo "Invalid action: ${{ github.event.inputs.action }}"
+            exit 1
+            fi
